---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: desnoite
description: Desnoite is a custom image for my personal use.

base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 43

modules:
  - type: files
    files:
      - source: system/etc
        destination: /etc

  - type: brew
    nofile-limits: true
    brew-analytics: true
    auto-update: true
    update-interval: '7d'

  - type: bling
    install:
      - rpmfusion

  - type: dnf
    repos:
      files:
        - emby.repo
        - emby-beta.repo
        - google-cloud-sdk.repo
        - vscode.repo
      nonfree: rpmfusion
    install:
      packages:
        - alacritty
        - chezmoi
        - code
        - direnv
        - distrobox
        - fzf
        - git
        - git-lfs
        - google-cloud-cli
        - htop
        - intel-media-driver
        - kamoso
        - libvirt-daemon
        - libvirt-nss
        - libva-utils
        - libxcrypt-compat
        - lm_sensors
        - lsof
        - media.emby.client.beta
        - mesa-va-drivers-freeworld
        - neovim
        - powertop
        - ripgrep
        - s-tui
        - steam-devices
        - strace
        - syncthing
        - tlp
        - tmux
        - unrar
        - unzip
        - virt-manager
        - wireshark
        - wget
        - zsh
    group-install:
      install-weak-deps: true
      exclude:
        - PackageKit-gstreamer-plugin
      packages:
        - development-tools
        - rpm-development-tools
        - container-management
        - multimedia
    remove:
      packages:
        - firefox
        - firefox-langpacks
    replace:
      - from-repo: rpmfusion-free
        allow-erasing: true
        packages:
          - old: ffmpeg-free
            new: ffmpeg
          - old: mesa-va-drivers
            new: mesa-va-drivers-freeworld

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
        - UbuntuMono
  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        repo:
          title: Fedora
          url: oci+https://registry.fedoraproject.org
          name: fedora
        install:
          - com.github.tchx84.Flatseal
          - org.fedoraproject.MediaWriter
          - org.gimp.GIMP
          - org.kde.elisa
          - org.keepassxc.KeePassXC
          - org.libreoffice.LibreOffice
          - org.mozilla.firefox
          - org.videolan.VLC
      - notify: false
        scope: user
        repo:
          title: Fedora
          url: oci+https://registry.fedoraproject.org
          name: fedora
        install:
          - org.kde.kdenlive
          - com.obsproject.Studio
          - com.obsproject.Studio.Plugin.Browser
          - com.obsproject.Studio.Plugin.DroidCam
          - com.obsproject.Studio.Plugin.VLCVideo
      - notify: false
        scope: system
        repo:
          title: Flathub
        install:
          - com.borgbase.Vorta
          - com.yubico.yubioath
          - im.riot.Riot
          - io.github.flattool.Warehouse
          - org.signal.Signal
          - org.telegram.desktop
      - notify: false # Send notification after install/uninstall is finished (true/false)
        scope: user
        repo:
          title: Flathub
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.obsproject.Studio.Plugin.Gstreamer
          - com.obsproject.Studio.Plugin.GStreamerVaapi
          - com.obsproject.Studio.Plugin.OBSVkCapture
          - com.spotify.Client
          - com.valvesoftware.Steam
          - io.podman_desktop.PodmanDesktop
          - md.obsidian.Obsidian
          - net.lutris.Lutris
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
