---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: desnoite
# description will be included in the image's metadata
description: Desnoite is a custom image for my personal use.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: brew
    nofile-limits: true
    brew-analytics: true
    auto-update: true
    update-interval: '7d'

  - type: bling
    install:
      - rpmfusion

  - type: dnf
    repos:
      files:
        - cursor.repo
        - emby.repo
        - emby-beta.repo
    install:
      packages:
        - alacritty
        - chezmoi
        - cursor
        - distrobox
        - fzf
        - git
        - git-lfs
        - golang
        - htop
        - intel-media-driver
        - kamoso
        - media.emby.client.beta.x86_64
        - mesa-va-drivers-freeworld
        - neovim
        - nix
        - powertop
        - ripgrep
        - s-tui
        - steam-devices
        - syncthing
        - tlp
        - tmux
        - unrar
        - unzip
        - wget
        - zsh
    group-install:
      packages:
        - development-tools
        - rpm-development-tools
        - container-management
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
        - UbuntuMono

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: user
        repo:
          title: Fedora
          url: oci+https://registry.fedoraproject.org
          name: fedora
        install:
          - org.kde.elisa
          - org.kde.kdenlive
          - org.mozilla.firefox
          - com.obsproject.Studio
          - com.obsproject.Studio.Plugin.Browser
          - com.obsproject.Studio.Plugin.DroidCam
          - com.obsproject.Studio.Plugin.VLCVideo
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: user
        repo:
          title: Flathub
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.borgbase.Vorta
          - com.obsproject.Studio.Plugin.Gstreamer
          - com.obsproject.Studio.Plugin.GStreamerVaapi
          - com.obsproject.Studio.Plugin.OBSVkCapture
          - com.spotify.Client
          - com.valvesoftware.Steam
          - com.yubico.yubioath
          - im.riot.Riot
          - io.podman_desktop.PodmanDesktop
          - md.obsidian.Obsidian
          - net.lutris.Lutris
          - org.fedoraproject.MediaWriter
          - org.gimp.GIMP
          - org.libreoffice.LibreOffice
          - org.signal.Signal
          - org.telegram.desktop
          - org.videolan.VLC

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
